aj_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    path('spotify/', include('spotify.urls')),                   # Add
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url


app_name='aj_web'
urlpatterns = [
    path('', views.MainView.as_view(), name='home'),

]

spotify/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

# https://docs.djangoproject.com/en/2.1/topics/http/urls/
app_name='spotify'
urlpatterns = [
    path('short_term_artists', views.ShortTermArtistsView.as_view(), name='short_term_artists'),
    path('medium_term_artists', views.MediumTermArtistsView.as_view(), name='medium_term_artists'),
    path('long_term_artists', views.LongTermArtistsView.as_view(), name='long_term_artists'),
    path('short_term_tracks', views.ShortTermTracksView.as_view(), name='short_term_tracks'),
    path('medium_term_tracks', views.MediumTermTracksView.as_view(), name='medium_term_tracks'),
    path('long_term_tracks', views.LongTermTracksView.as_view(), name='long_term_tracks'),
    path('', views.MainView.as_view(), name='all'),


]

home/models.py
from django.db import models

# Create your models here.

spotify/models.py
from django.db import models

# Create your models here.

home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from spotify import spotify
# Create your views here.

class MainView(LoginRequiredMixin, View) :
    def get(self, request):
        return render(request, 'home/home.html')

spotify/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from spotify.spotify import createHTMLFile
from rest_framework.authtoken.views import ObtainAuthToken
import spotipy
import logging
import json
from social_django.models import UserSocialAuth
import spotipy.util as util
from django.contrib.auth import logout


class MainView(LoginRequiredMixin, View) :
    def get(self, request):
        user = request.user
        auth_json = request.user.social_auth.values_list('extra_data')
        auth_json = auth_json[0][0]
        token = auth_json['access_token']

        username = request.user.social_auth.values_list('uid')[0][0]

        spotify_obj = spotipy.Spotify(auth=token)
        print(spotify_obj._auth)
        print(token)

        createHTMLFile('Artists', 'short_term', spotify_obj)

        #return render(request, createHTMLFile('Artists', 'short_term', spotify_obj))
        return render(request, 'spotify/spotify_user_list.html')


class ShortTermArtistsView(LoginRequiredMixin, View) :
    def get(self, request):
        user = request.user
        auth_json = request.user.social_auth.values_list('extra_data')
        auth_json = auth_json[0][0]
        token = auth_json['access_token']

        username = request.user.social_auth.values_list('uid')[0][0]
        try:
            spotify_obj = spotipy.Spotify(auth=token)
            createHTMLFile('Artists', 'short_term', spotify_obj)
        except:
            logout(request)



        return render(request, 'spotify/spotify_user_list.html')

class MediumTermArtistsView(LoginRequiredMixin, View) :
    def get(self, request):
        user = request.user
        auth_json = request.user.social_auth.values_list('extra_data')
        auth_json = auth_json[0][0]
        token = auth_json['access_token']

        username = request.user.social_auth.values_list('uid')[0][0]
        try:
            spotify_obj = spotipy.Spotify(auth=token)
            createHTMLFile('Artists', 'medium_term', spotify_obj)
        except:
           logout(request)

        return render(request, 'spotify/spotify_user_list.html')


class LongTermArtistsView(LoginRequiredMixin, View) :
    def get(self, request):
        user = request.user
        auth_json = request.user.social_auth.values_list('extra_data')
        auth_json = auth_json[0][0]
        token = auth_json['access_token']

        username = request.user.social_auth.values_list('uid')[0][0]
        try:
            spotify_obj = spotipy.Spotify(auth=token)
            createHTMLFile('Artists', 'long_term', spotify_obj)
        except:
            logout(request)


        return render(request, 'spotify/spotify_user_list.html')

class ShortTermTracksView(LoginRequiredMixin, View) :
    def get(self, request):
        user = request.user
        auth_json = request.user.social_auth.values_list('extra_data')
        auth_json = auth_json[0][0]
        token = auth_json['access_token']

        username = request.user.social_auth.values_list('uid')[0][0]
        try:
            spotify_obj = spotipy.Spotify(auth=token)
            createHTMLFile('Tracks', 'short_term', spotify_obj)
        except:
            logout(request)
            # from social_django.utils import load_strategy
            # social = user.social_auth.get(provider='spotify')
            # strategy = load_strategy()
            # auth_json = request.user.social_auth.values_list('extra_data')
            # auth_json = auth_json[0][0]
            # token = auth_json['access_token']
            # spotify_obj = spotipy.Spotify(auth=token)

        return render(request, 'spotify/spotify_user_list.html')

class MediumTermTracksView(LoginRequiredMixin, View) :
    def get(self, request):
        user = request.user
        auth_json = request.user.social_auth.values_list('extra_data')
        auth_json = auth_json[0][0]
        token = auth_json['access_token']

        username = request.user.social_auth.values_list('uid')[0][0]
        try:
            spotify_obj = spotipy.Spotify(auth=token)
            createHTMLFile('Tracks', 'medium_term', spotify_obj)
        except:
            logout(request)

        return render(request, 'spotify/spotify_user_list.html')

class LongTermTracksView(LoginRequiredMixin, View) :
    def get(self, request):
        user = request.user
        auth_json = request.user.social_auth.values_list('extra_data')
        auth_json = auth_json[0][0]
        token = auth_json['access_token']

        username = request.user.social_auth.values_list('uid')[0][0]
        try:
            spotify_obj = spotipy.Spotify(auth=token)
            createHTMLFile('Tracks', 'long_term', spotify_obj)
        except:
            logout(request)


        return render(request, 'spotify/spotify_user_list.html')

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
    <!-- Edit samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->




<link rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
   crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  crossorigin="anonymous"></script>

<script
  src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">



<meta name="wa4e-version" value="2019-10:161EB">




    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        {% load static %}
  <a style ="width:30%" class="navbar-brand" href=""><img src="{% static 'images/spoti_stats_logo_hor.png' %}" id="logo" alt="Spoti Stats Logo"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">


    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown" >
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Top Artists
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <table>
            <tr>
            <td class="numbering">
                <div id="home_link_tabs">
          <a class="dropdown-item" href="spotify/long_term_artists">Long Term Artists</a>
          <a class="dropdown-item" href="spotify/medium_term_artists">Medium Term Artists</a>
          <!--<div class="dropdown-divider"></div> -->
          <a class="dropdown-item" href="spotify/short_term_artists">Short Term Artists</a>

        </div>
        </td>
        </tr>
        </table>

      </li>

      <li class="nav-item dropdown" >
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Top Tracks
        </a>

        <table>
            <tr>
            <td class="numbering">
                <div id="home_link_tabs">

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <a class="dropdown-item" href="spotify/long_term_tracks">Long Term Tracks</a>



          <a class="dropdown-item" href="spotify/medium_term_tracks">Medium Term Tracks</a>



          <a class="dropdown-item" href="spotify/short_term_tracks">Short Term Tracks</a>



          </div>
          </td>
        </tr>
        </table>


      </li>


        <li class="nav-item active" >
                <a class="nav-link" href="{% url 'logout' %}?next={% url 'spotify:all' %}">Logout <span class="sr-only">(current)</span></a>
        </li>



    </ul>


  </div>





</nav>






</head>
<body>
{% block navbar %} {% endblock %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

home/templates/home/home.html
 {% extends "base_bootstrap.html" %} {% block navbar %}

<!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>Spoti Stats Homepage</title>

        {% load static %}
        <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

    </head>

<main>

<body>
    <br>
    <br>
    <h1>Welcome to</h1>


    {% load static %}

        <img src="{% static 'images/spoti_stats_logo_hor.png' %}" id="logo" alt="Spoti Stats Logo">


        <h2>Check Out Your Listening Habits</h2>

        <img class= "trends_logo"src="{% static 'images/artist_trends.png' %}" alt="Artist Trends Logo">


        <table>
            <tr>
                <td class="numbering">
    <div id="home_link_tabs">
        <a class="dropdown-item"  href="spotify/long_term_artists" title="View Top Long Term Streamed Artists">View Top Long Term Streamed Artists</a>
</div>
</td>


        <td class="numbering">
        <div id="home_link_tabs">
        <a class="dropdown-item" href="spotify/medium_term_artists" title="View Medium Term Streamed Artists">View Medium Term Streamed Artists</a>
        </div>
        </td>

        <td class="numbering">
        <div id="home_link_tabs">
        <a class="dropdown-item" href="spotify/short_term_artists" title="View Short Term Streamed Artists">View Short Term Streamed Artists</a>
        </div>
        </td>
        </tr>

        </table>

        <br>

        <img class= "trends_logo" src="{% static 'images/track_trends.png' %}" alt="Track Trends Logo">

        <table>
            <tr>

            <td class="numbering">
        <div id="home_link_tabs">
        <a class="dropdown-item" href="spotify/long_term_tracks" title="View Long Term Streamed Tracks">View Long Term Streamed Tracks</a>
        </div>
        </td>

        <td class="numbering">
        <div id="home_link_tabs">
        <a class="dropdown-item" href="spotify/medium_term_tracks" title="View Medium Term Streamed Tracks">View Medium Term Streamed Tracks</a>
        </div>
        </td>

        <td class="numbering">
        <div id="home_link_tabs">
        <a class="dropdown-item" href="spotify/short_term_tracks" title="View Short Term Streamed Tracks">View Short Term Streamed Tracks</a>
        </div>
        </td>


        </table>





   <div class="home_content">
        <h2>What is Spoti Stats?</h1>
            <p> No more having to wait to the end of the year for your Spotify Unwrapped.<br> This web app is a fun way to check your own listening trends on your own terms.<br> It's built using the Spotify API to scrape user listening data.</p>
            <p class="no_padding">Currently, Spoti Stats is able to grab your top tracks and top artists within three different time intervals (short term, medium term, and long term listening history).</p>

            {% load static %}

        <div id="gallery">
            <div class="row">
                <div class="column">
                    <img src="{% static 'images/track.jpg' %}" alt="Track Stats Screenshot">
                </div>
                <div class="column">
                    <img src="{% static 'images/artist.jpg' %}" alt="Artist Stats Screenshot">
                </div>

            </div>

            </div>
    </div>










</body>

</main>

<footer>

            <p>AJ Carter &copy; 2020</p>
            </footer>


</html>

{% endblock %}